### PR TITLE
feat: cleanup logic to remove files when user is disconnected

### PR DESCRIPTION
**Pull request by pradhumngautam**
fix: issue #7

### CODE REVIEW

**Comment by hkirat** [comment]
you've commited dist, mind removing it?

**Comment by pradhumngautam** [comment]
Yes,sure @hkirat

**Comment by pradhumngautam** [comment]
> you've commited dist, mind removing it?

created pr #9

**Comment by pradhumngautam** [comment]
created new pr #9 @hkirat

**Pull request closed without merging**
